apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80          # External Port
      targetPort: 5000  # Container Port
  type: LoadBalancer    # Use NodePort if not using cloud LB

